# Generated by Django 3.1.1 on 2020-09-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_auto_20200910_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='pin_code',
            field=models.CharField(max_length=10),
        ),
    ]
