# Generated by Django 3.1.1 on 2020-09-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_in_warranty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='screen_size',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
