# Generated by Django 3.1.1 on 2020-09-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200911_1245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='gpu',
            new_name='extra_gpu',
        ),
    ]
