# Generated by Django 3.1.1 on 2020-09-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_auto_20200911_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ram',
            field=models.CharField(default='2 GB', max_length=255),
        ),
    ]
