# Generated by Django 3.1.1 on 2020-09-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_ram'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='extra_gpu',
        ),
        migrations.AddField(
            model_name='listing',
            name='graphics_type',
            field=models.CharField(default='Integrated', max_length=255),
        ),
        migrations.AddField(
            model_name='listing',
            name='memory',
            field=models.CharField(default='256GB HDD', max_length=255),
        ),
    ]
