# Generated by Django 3.1.1 on 2020-09-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200911_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='specifications',
            new_name='condition_description',
        ),
        migrations.AddField(
            model_name='listing',
            name='other_specifications',
            field=models.TextField(blank=True),
        ),
    ]
